# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Laurence Midgley
description: >- # this means to ignore newlines until "baseurl:"
 Silly goose
baseurl: "" # the subpath of the site
url: "https://laurencemidgley.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
#    - name: Work
#      slug: /work
    - name: Publications & Talks
      slug: /publications

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: laurencemidgley@gmail.com
      link: mailto:laurencemidgley@gmail.com
      logo: fas fa-envelope
  follow:
    - name: Twitter
      link: http://twitter.com/SilkyDogfish
      logo: fab fa-twitter
      username: "@SilkyDogfish"
    - name: GitHub
      link: http://github.com/lollcat
      logo: fab fa-github
    - name: Scholar
      logo: ai ai-google-scholar-square
      link: https://scholar.google.com/citations?user=vMd1gwMAAAAJ&hl=en

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
